version: "3.8"

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=LMS
      - MYSQL_USER=ash
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=mypassword